# Generated by Django 2.1.7 on 2019-04-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190318_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='location',
            new_name='vineyard_location',
        ),
        migrations.RenameField(
            model_name='producer',
            old_name='location',
            new_name='winery_location',
        ),
    ]
